tools:
  - class_name: "verl.tools.sandbox_fusion_tools_txt_w_reward.SandboxFusionTool"
    config: 
      sandbox_fusion_url: "http://xxx.xxx.xxx.xxx:8080/run_code" 
      num_workers: 10
      enable_global_rate_limit: true
      rate_limit: 10
      default_timeout: 30
      default_language: "python"
      memory_limit_mb: 10240
      type: native

    tool_schema:
      type: "function"
      function:
        name: "code_interpreter"
        description: "A tool for executing code."
        parameters:
          type: "object"
          properties:
            code:
              type: "string"
              description: "The code to execute."
          required: ["code"]
